# Assignment

Q1. Write the NumPy program to create a 2d array with 6 on the border
and 0 inside?

    Expected OutputOriginal array-
    [ [6 6 6 6 6]
     [ 6 6 6 6 6]
     [ 6 6 6 6 6 ]
    [ 6 6 6 6 6 ]
    [ 6 6 6 6 ] ].
    6 on the border and 0 inside in the array-
    [[ 6 6 6 6 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 6 6 6 6]].

In [22]:
import numpy as np

my_array= np.ones((6,5), dtype = int) * 6
my_array[1:-1,1:-1] = 0
print(my_array)

[[6 6 6 6 6]
 [6 0 0 0 6]
 [6 0 0 0 6]
 [6 0 0 0 6]
 [6 0 0 0 6]
 [6 6 6 6 6]]


Q2. Write the NumPy program to create a 8x8 matrix and fill it with the
checkerboard pattern?
    
    Checkerboard pattern-
    [[3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]].

In [21]:
import numpy as np

my_array= np.ones((8,8), dtype = int) * 3
my_array[1::2,0::2] = my_array[1::2,0::2] * 3
my_array[0::2,1::2] = my_array[0::2,1::2] * 3
print(my_array)

[[3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]]


Q3. Write the NumPy program to create an empty and a full array.
 
     Expected Output-
    [[4.45057637e-308 1.78021527e-306 8.45549797e-307 1.37962049e-306]
    [1.11260619e-306 1.78010255e-306 9.79054228e-307 4.45057637e-308]
    [8.45596650e-307 9.34602321e-307 4.94065646e-322 0.00000000e+000]]
    [[6 6 6]
    [6 6 6]
    [6 6 6]]


In [28]:
import numpy as np
empty_array = np.empty((3,3))
print("Empty Array is :\n", empty_array)

full_array = np.full((3,3), 6)
print("\nFull Array is :\n", full_array)

Empty Array is :
 [[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 7.49003519e-321]
 [6.36598737e-314 6.36598737e-314 2.12199579e-314]]

Full Array is :
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


Q4. Write the NumPy program to convert the values of Centigrade
degrees into the Fahrenheit degrees and the centigrade values are
stored in the NumPy array.
    
    Sample Array -[0, 12, 45.21 ,34, 99.91]
    Expected OutputValues in Fahrenheit degrees-
    [ 0. 12. 45.21 34. 99.91]
    Values in Centigrade degrees-
    [-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778]

In [40]:
def fah_to_cel(input_fah_array):
    return (input_fah_array -32) * (5 / 9)

def cel_to_fah(input_cel_array):
    return (input_cel_array * (9 / 5)) + 32

fah_array = np.array([0, 12, 45.21 ,34, 99.91])
print("The Fahrenheit array is: ", fah_array)

cel_array = fah_to_cel(fah_array)
print("The Fahrenheit to Celsius conversion is: ", cel_array)

fah_array = cel_to_fah(cel_array)
print("The Celsius to Fahrenheit conversion is: ", fah_array)


The Fahrenheit array is:  [ 0.   12.   45.21 34.   99.91]
The Fahrenheit to Celsius conversion is:  [-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]
The Celsius to Fahrenheit conversion is:  [ 0.   12.   45.21 34.   99.91]


Q5. Write the NumPy program to find the real and imaginary parts of an
array of complex numbers?

    Expected OutputOriginal array [ 1.00000000+0.j 0.70710678+0.70710678j]
    Real part of the array-
    [ 1. 0.70710678]
    Imaginary part of the array-
    [ 0. 0.70710678]

In [47]:
input_array = np.array([ 1.00000000+0.j, 0.70710678+0.70710678j])
print("Real part of the array is: ", input_array.real)
print("Imaginary part of the array is: ", input_array.imag)

Real part of the array is:  [1.         0.70710678]
Imaginary part of the array is:  [0.         0.70710678]


Q6. Write the NumPy program to test whether each element of a 1-D
array is also present in the second array?

    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [0, 40]
    Compare each element of array1 and array2
    [ True False False True False]


In [161]:
array1 = np.array([ 0, 10, 20, 40, 60])
array2 = np.array([0, 40])

print("Comparing each element of array1 and array2:")
print(np.in1d(array1, array2))

Comparing each element of array1 and array2:
[ True False False  True False]


Q7. Write the NumPy program to find common values between two
arrays?
    
    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [10, 30, 40]
    Common values between two arrays-
    [10 40]

In [57]:
array1 = np.array([ 0, 10, 20, 40, 60])
array2 = np.array([10, 30, 40])

print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Common values between two arrays:
[10 40]


Q8. Write the NumPy program to get the unique elements of an array?

    Expected OutputOriginal array-
    [10 10 20 20 30 30]
    Unique elements of the above array-
    [10 20 30]
    P a g e 14 | 44
    Original array-
    [[1 1]
    [2 3]]
    Unique elements of the above array-
    [1 2 3]

In [62]:
array1 = np.array([ 10, 10, 20, 20, 30, 30])
array2 = np.array([[1, 1], [2, 3]])

print("Unique elements of the array1")
print(np.unique(array1))

print("\nUnique elements of the array2")
print(np.unique(array2))

Unique elements of the array1
[10 20 30]

Unique elements of the array2
[1 2 3]


Q9. Write the NumPy program to find the set exclusive-or of two arrays.
Set exclusive-or will return the sorted, unique values that are in
only one (not both) of the input arrays?

    Array1- [ 0 10 20 40 60 80]
    Array2- [10, 30, 40, 50, 70]
    Unique values that are in only one (not both) of the input arrays-
    [ 0 20 30 50 60 70 80]

In [63]:
Array1 = np.array([ 0, 10, 20, 40, 60, 80])
Array2 = np.array([10, 30, 40, 50, 70])

print("Unique values that are in only one (not both) of the input arrays:")
print(np.setxor1d(Array1, Array2))


Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]


Q10. Write the NumPy program to test if all elements in an array
evaluate to True ?
 
Note: 0 evaluates to False in NumPy

In [75]:
array1 = np.array([ 0, 10, 20, 40, 60, 80])
aArray2 = np.array([10, 30, 40, 50, 70])

print(np.all(array1))
print(np.all(array2))

False
True


Q11. Write the NumPy program to test whether any array element along
the given axis evaluates to True?
 
Note: 0 evaluates to False in NumPy

In [97]:
np.random.seed(1)
array1 = np.random.randint(0,9,16).reshape(4,-1)
print("The array is: \n", array1)
print("\nTest along axis = 0\n", np.all(array1, 0))
print("\nTest along axis = 1\n", np.all(array1, 1))

The array is: 
 [[5 8 5 0]
 [0 1 7 6]
 [2 4 5 2]
 [4 2 4 7]]

Test along axis = 0
 [False  True  True False]

Test along axis = 1
 [False False  True  True]


Q12. Write the NumPy program to construct an array by repeating?

    Sample array- [1, 2, 3, 4]
    Expected OutputOriginal array
    [1, 2, 3, 4]
    Repeating 2 times
    [1 2 3 4 1 2 3 4]
    Repeating 3 times
    [1 2 3 4 1 2 3 4 1 2 3 4]

In [100]:
array1 = np.array([1, 2, 3, 4])

print("Input Array:\n", array1)

print("\nRepeating 2 times\n", np.tile(array1, 2))

print("\nRepeating 3 times\n", np.tile(array1, 3))

Input Array:
 [1 2 3 4]

Repeating 2 times
 [1 2 3 4 1 2 3 4]

Repeating 3 times
 [1 2 3 4 1 2 3 4 1 2 3 4]


Q13. Write the NumPy program to find the indices of the maximum and
minimum values with the given axis of an array?

    Original array- [1 2 3 4 5 6]
    Maximum Values- 5
    Minimum Values- 0

In [110]:
array1 = np.array([1, 2, 3, 4, 5, 6])
print("The index of maximum value is: ", np.argmax(array1))
print("The index of minimum value is: ", np.argmin(array1))

The index of maximum value is:  5
The index of minimum value is:  0


Q14. Write the NumPy program compare two arrays using numpy?

    Array a- [1 2]
    Array b- [4 5]
    a > b
    [False False]
    a >= b
    [False False]
    a < b
    [ True True]
    a <= b
    [ True True]


In [125]:
array1 = np.array([1, 2, 7])
array2 = np.array([1, 5, 4])

print("Is array1 > array2 : ", np.greater(array1, array2))
print("Is array1 >= array2 : ", np.greater_equal(array1, array2))

print("Is array1 < array2 : ", np.less(array1, array2))
print("Is array1 <= array2 : ", np.less_equal(array1, array2))

Is array1 > array2 :  [False False  True]
Is array1 >= array2 :  [ True False  True]
Is array1 < array2 :  [False  True False]
Is array1 <= array2 :  [ True  True False]


Q15. Write the NumPy program to sort an along the first, last axis of an
array?

    Sample array- [[2,5],[4,4]]
    Expected OutputOriginal array:
    [[4 6]
    [2 1]]
    Sort along the first axis:
    [[2 1]
    [4 6]]
    Sort along the last axis-
    [[1 2]
    [4 6]]

In [139]:
np.random.seed(1)
array1 = np.random.randint(0,9,16).reshape(4,-1)

print("The array is: \n", array1)

print("\nSorting along axis = 0: \n", np.sort(array1, axis = 0))
      
print("\nSorting along axis = 1: \n", np.sort(array1, axis = 1))

The array is: 
 [[5 8 5 0]
 [0 1 7 6]
 [2 4 5 2]
 [4 2 4 7]]

Sorting along axis = 0: 
 [[0 1 4 0]
 [2 2 5 2]
 [4 4 5 6]
 [5 8 7 7]]

Sorting along axis = 1: 
 [[0 5 5 8]
 [0 1 6 7]
 [2 2 4 5]
 [2 4 4 7]]


Q16. Write the NumPy program to sort pairs of first name and last name
return their indices (first by last name, then by first name).

    first_names - ( Betsey, Shelley, Lanell, Genesis, Margery )
    last_names - ( Battle, Brien, Plotner, Stahl, Woolum )
    Expected Output-
    [1 3 2 4 0]

In [141]:
import numpy as np
first_names =    ('Margery', 'Betsey', 'Shelley', 'Lanell', 'Genesis')
last_names = ('Woolum', 'Battle', 'Plotner', 'Brien', 'Stahl')
out = np.lexsort((first_names, last_names))
print(out)

[1 3 2 4 0]


Q17. Write the NumPy program to get the values and indices of the
elements that are bigger than 10 in the given array?

    Original array-
    [[ 0 10 20]
    [20 30 40]]
    Values bigger than 10 = [20 20 30 40]
    Their indices are (array([0, 1, 1, 1]), array([2, 0, 1, 2]))

In [148]:
array1 = np.array([[0, 10, 20], [20, 30, 40]])

print("Values bigger than 10: \n", array1[array1>10])
print("\nTheir indices are: \n", np.where(array1 > 10))

Values bigger than 10: 
 [20 20 30 40]

Their indices are: 
 (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


Q18. Write the NumPy program to find the memory size of a NumPy
array?

    Expected Output128 bytes


In [160]:
np.random.seed(1)
array1 = np.random.randint(100,900,16).reshape(4,-1)
print(array1.itemsize * array1.size, "bytes")

64 bytes


## Great Job!